version: "3.8"
services:
  groufie-server:
    build:
      context: ./groufie/ # path of root directory
      dockerfile: ./Dockerfile # path relative to root directory
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - blem-network
  imagehippo-server:
    build:
      context: ./imagehippo/ # path of root directory
      dockerfile: ./Dockerfile # path relative to root directory
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - blem-network
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./docker/volumes/caddy/data:/data
      - ./docker/volumes/caddy/config:/config
      - ./docker/volumes/caddy/logs:/var/log/caddy/
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - blem-network
    depends_on:
      - groufie-server
      - imagehippo-server
networks:
  blem-network:
    name: blem-network
