version: "3.8"
services:
  blem-server:
    build:
      context: ./landing/ # path of root directory
      dockerfile: ./Dockerfile # path relative to root directory
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - blem-network
  groufie-server:
    build:
      context: ./groufie/ # path of root directory
      dockerfile: ./Dockerfile # path relative to root directory
    restart: unless-stopped
    ports:
      - 3003:3003
    networks:
      - blem-network
  tasks-server:
    build:
      context: ./tasks/ # path of root directory
      dockerfile: ./Dockerfile # path relative to root directory
    restart: unless-stopped
    ports:
      - 3004:3004
    environment:
      POSTGRES_HOST: postgres
    networks:
      - blem-network
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/volumes/postgres/entrypoint:/docker-entrypoint-initdb.d
      - ./docker/volumes/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - blem-network
  imagehippo-server:
    build:
      context: ./imagehippo/ # path of root directory
      dockerfile: ./Dockerfile # path relative to root directory
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - blem-network
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./docker/volumes/caddy/data:/data
      - ./docker/volumes/caddy/config:/config
      - ./docker/volumes/caddy/logs:/var/log/caddy/
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - blem-network
    depends_on:
      - groufie-server
      - imagehippo-server
      - blem-server
      - tasks-server
      -
networks:
  blem-network:
    name: blem-network
