version: "3.8"
services:
  blem-server:
    build:
      context: ./landing/ # path of root directory
      dockerfile: ./Dockerfile # path relative to root directory
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - blem-network
  groufie-server:
    build:
      context: ./groufie/ # path of root directory
      dockerfile: ./Dockerfile # path relative to root directory
    restart: unless-stopped
    ports:
      - 3003:3003
    networks:
      - blem-network
  tasks-server:
    build:
      context: ./tasks/ # path of root directory
      dockerfile: ./Dockerfile # path relative to root directory
    restart: unless-stopped
    ports:
      - 3004:3004
    networks:
      - blem-network
  imagehippo-server:
    build:
      context: ./imagehippo/ # path of root directory
      dockerfile: ./Dockerfile # path relative to root directory
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - blem-network
  hippodirect-typesense:
    image: typesense/typesense:0.25.2
    ports:
      - 8108:8108
    environment:
      TYPESENSE_DATA_DIR: /var/lib/typesense/data
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY:?error}
      TYPESENSE_API_PORT: 8108
      TYPESENSE_ENABLE_CORS: true
    volumes:
      - ./docker/volumes/typesense/data:/var/lib/typesense/data
    networks:
      - blem-network
  hippodirect-server:
    build:
      context: ./hippodirect/ # path of root directory
      dockerfile: ./Dockerfile # path relative to root directory
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY:?error}
    restart: unless-stopped
    ports:
      - 3002:3002
    networks:
      - blem-network
    depends_on:
      - hippodirect-typesense
    volumes:
      - ./hippodirect/server:/app
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./docker/volumes/caddy/data:/data
      - ./docker/volumes/caddy/config:/config
      - ./docker/volumes/caddy/logs:/var/log/caddy/
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - blem-network
    depends_on:
      - groufie-server
      - imagehippo-server
      - hippodirect-server
      - blem-server
      - tasks-server
  postgres-server:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blem-network
volumes:
  postgres_data:
networks:
  blem-network:
    name: blem-network
